# example of how to run deployment version of Gens
services:
  mongodb:
    image: mongo:4.4.9
    networks:
      - gens-net
  gens:
    build: .
    volumes:
      - ./volumes/gens/data:/home/app/data
      - ./volumes/gens/wgs:/home/app/access/wgs
    expose:
      - '5000'
    ports:
      - "5000:5000"
    networks:
      - gens-net
    depends_on:
      - mongodb
networks:
  gens-net:
    driver: bridge
